[package]
name = "boot-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boot-lib = { path = "../boot-lib" }
uefi = { version = "0.19.0", features = ["alloc"] }
uefi-services = "0.16.0"